"""add user_id to skill_synonyms

Revision ID: 6ceda58dd4f6
Revises: c0b341a98398
Create Date: 2026-01-11 10:57:52.820261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ceda58dd4f6'
down_revision = 'c0b341a98398'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_synonyms', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'skill_synonyms', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill_synonyms', type_='foreignkey')
    op.drop_column('skill_synonyms', 'user_id')
    # ### end Alembic commands ###
