"""Add embedding field to resumes

Revision ID: b2a08b5c908c
Revises: 6ceda58dd4f6
Create Date: 2026-01-12 10:33:43.756452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a08b5c908c'
down_revision = '6ceda58dd4f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'embedding')
    # ### end Alembic commands ###
