"""Add skill_synonyms table

Revision ID: c0b341a98398
Revises: c342e3d3e4cd
Create Date: 2026-01-11 10:16:45.924811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b341a98398'
down_revision = 'c342e3d3e4cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_synonyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('synonym', sa.String(), nullable=False),
    sa.Column('canonical_skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_synonyms_id'), 'skill_synonyms', ['id'], unique=False)
    op.create_index(op.f('ix_skill_synonyms_synonym'), 'skill_synonyms', ['synonym'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_synonyms_synonym'), table_name='skill_synonyms')
    op.drop_index(op.f('ix_skill_synonyms_id'), table_name='skill_synonyms')
    op.drop_table('skill_synonyms')
    # ### end Alembic commands ###
